---
apiVersion: v1
kind: Service
metadata:
  name: use-custom-start-service
  labels:
    app: use-custom-start-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
      protocol: TCP
  clusterIP: None
  selector:
    app: use-custom-start-service
  type: ClusterIP
